version: 2.1
orbs:
  node: circleci/node@5.0.1
  aws-cli: circleci/aws-cli@2.1.0
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
        name: install the backend node-modules 
        command: | 
          npm run backend:install
workflows:
    build_deploy:
      jobs:
        - build:
            filters:
              branches:
                only:
                  - main